schema_version: 1

context:
  name: types-pyRFC3339
  version: 2.0.1.20250825

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') | lower }}-${{ version }}.tar.gz
  sha256: 954797ad8262e93eca99a6015efdbbf6d4028a0e9e460ab82ef8d440dd7b5480

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

  - package_contents:
      site_packages:
        - pyrfc3339-stubs/__init__.pyi

about:
  summary: Typing stubs for pyRFC3339
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
